# Generated by Django 5.0.3 on 2024-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_remove_voter_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='lname',
            field=models.IntegerField(),
        ),
    ]
